services:
  inp0st_org:
    image: inp0st_org
    build:
      context: .
      dockerfile: Dockerfile
    container_name: Inp0st_org_container
    env_file:
      - .env
    environment:
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
    stdin_open: true
    tty: true